apiVersion: apps.adetalhouet.io/v1alpha1
kind: OrderSystem
metadata:
  name: test
spec:
  initialized: false
  valid: true
  error: false
  autoscaleEnabled: false
  injectIstioSidecarEnabled: false
  version: "1.0.0"