apiVersion: apps.adetalhouet.io/v1alpha1
kind: OrderSystem
metadata:
  name: test
spec:
  autoscaleEnabled: true
  injectIstioSidecarEnabled: false
  version: "1.0.0"
  nats:
    credentialSecretName: "order-system-crendentials"
    serviceName: "order-system-nats-client"
  postgres:
     credentialSecretName: "order-system-crendentials"
     serviceName: "order-system-db-postgresql" 