# permissions for end users to edit ordersystems.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ordersystem-editor-role
rules:
- apiGroups:
  - apps.adetalhouet.io
  resources:
  - ordersystems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.adetalhouet.io
  resources:
  - ordersystems/status
  verbs:
  - get
