# permissions for end users to view ordersystems.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ordersystem-viewer-role
rules:
- apiGroups:
  - apps.adetalhouet.io
  resources:
  - ordersystems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.adetalhouet.io
  resources:
  - ordersystems/status
  verbs:
  - get
